
transforms: {
    "_train": ["utterance_cmvn", "specaugment"],
    "*": ["utterance_cmvn"]
}

bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: spm.model

src_word_bpe_tokenizer:
  bpe: sentencepiece
  sentencepiece_model: spm_ende.model

utterance_cmvn:
        norm_means: True
        norm_vars: True

specaugment:
        time_wrap_W: 0
        freq_mask_N: 1
        freq_mask_F: 27
        time_mask_N: 1
        time_mask_T: 100
        time_mask_p: 1.0

prepend_tgt_lang_tag: false

input_channels: 1
input_feat_per_channel: 80

vocab_filename: dict.txt
src_vocab_filename: src_dict.txt
src_phone_vocab_filename: src_dict.txt
src_char_vocab_filename: dict_c.en.txt
src_word_vocab_filename: spm_ende_dict.txt
